# Generated by Django 5.2 on 2025-06-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='created_by',
            field=models.CharField(default='系統', max_length=100),
        ),
        migrations.AddField(
            model_name='revenue',
            name='notes',
            field=models.TextField(blank=True, help_text='備註說明'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已核准'), ('rejected', '已駁回')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='revenue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='updated_by',
            field=models.CharField(default='系統', max_length=100),
        ),
        migrations.CreateModel(
            name='RevenueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '刪除'), ('approve', '核准'), ('reject', '駁回')], max_length=20)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='變更說明')),
                ('changed_by', models.CharField(default='系統', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mock_data.revenue')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_data.store')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
