# Generated by Django 5.2 on 2025-06-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_data', '0002_revenue_created_by_revenue_notes_revenue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='status',
            field=models.CharField(choices=[('pending', '未提交'), ('submitted', '已提交')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='revenuelog',
            name='action',
            field=models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '刪除'), ('submit', '提交')], max_length=20),
        ),
    ]
