# Generated by Django 5.2 on 2025-06-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_data', '0003_alter_revenue_status_alter_revenuelog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.CharField(choices=[('taipei', '台北地區'), ('new_taipei', '新北地區'), ('taoyuan', '桃園地區'), ('taichung', '台中地區'), ('tainan', '台南地區'), ('kaohsiung', '高雄地區')], default='taipei', max_length=20),
        ),
    ]
